services:
   postgres-service:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_DB=testDb
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data/ 
   mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - 27017:27017
    volumes:
      - /var/lib/mongodb/data
   rabbitmq: 
    image: rabbitmq:3.12-management-alpine
    ports:
        - 5673:5672
        - 15673:15672
    volumes:
        - /var/lib/rabbitmq/